before_script:
   - docker info
stages:
  - build
  - unit-test
job1:
  stage: build
  tags:
    - golang
  script:
   - >
     docker run --rm -v $(pwd):/go/src/area-china-api -w /go/src/area-china-api pangpanglabs/golang:builder 
     bash -c 'git -C $GOPATH/src/github.com/pangpanglabs/echoswagger pull  && 
     go get -v -d && go build'
  only:
    - merge_requests
job2:
  stage: unit-test
  tags:
    - golang
  script:
   - $GOPATH/rtc/run-test-container run area-china-api -c msl
   - >
     docker run --rm -v $(pwd):/go/src/area-china-api -w /go/src/area-china-api 
     --add-host=test-kafka:10.202.101.230 
     -e APP_ENV=test-server -e JWT_SECRET=$JWT_SECRET
     pangpanglabs/golang:builder 
     bash -c 'git -C $GOPATH/src/github.com/pangpanglabs/echoswagger pull  && 
     go get -v -d && go test -p 1 -count 1 -v -coverpkg=./... -coverprofile coverage.out ./... && go tool cover -func=coverage.out'
  coverage: '/\d+\.\d+%/'
  only:
    - merge_requests