database:
  driver: mysql
  connection: root:1234@tcp(127.0.0.1:3306)/area_china?charset=utf8&parseTime=True&loc=UTC
  name: area-china-api
  logger:
    kafka:
      brokers:
        - 127.0.0.1:9092
      topic: sqllog
eventBroker:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: area-china-api
behaviorLog:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: behaviorlog
serviceName: area-china-api
httpport: 8080