envs:
  - APP_ENV=test
  - SQL_DRIVER=mysql
  - FRUIT_CONN=root:1234@tcp(test-mysql:3306)/fruit
isProjectKafka: false
ports: 
  - 8080
databases:
  mysql:
    - fruit
streamNames:
execPath: 